# Header
menu:
  Home: /
  Archives: /archives
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false #原本是true @webber

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
- tagcloud
- archive

# Miscellaneous
google_analytics:
favicon: /favicon.png
twitter:
google_plus:
fb_admins:
fb_app_id:
